# Generated by Django 5.0 on 2023-12-12 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('internal_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('guest_ID', models.BigIntegerField(blank=True, null=True)),
                ('active', models.CharField(blank=True, max_length=256, null=True)),
                ('first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('county', models.CharField(blank=True, max_length=256, null=True)),
                ('phone', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('number_in_household', models.BigIntegerField(blank=True, null=True)),
                ('authorized_representative_1', models.CharField(blank=True, max_length=256, null=True)),
                ('authorized_representative_2', models.CharField(blank=True, max_length=256, null=True)),
                ('authorized_representative_3', models.CharField(blank=True, max_length=256, null=True)),
                ('authorized_representative_4', models.CharField(blank=True, max_length=256, null=True)),
                ('authorized_representative_5', models.CharField(blank=True, max_length=256, null=True)),
                ('tefap_signature_date', models.CharField(blank=True, max_length=256, null=True)),
                ('tefap_signature', models.TextField(blank=True, null=True)),
                ('language_preference', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=256, null=True)),
                ('who_performed_pickup', models.CharField(blank=True, max_length=256, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('fns', models.CharField(blank=True, max_length=256, null=True)),
                ('number_in_household', models.BigIntegerField(blank=True, null=True)),
                ('yearly_income', models.CharField(blank=True, max_length=256, null=True)),
                ('monthly_income', models.CharField(blank=True, max_length=256, null=True)),
                ('weekly_income', models.CharField(blank=True, max_length=256, null=True)),
                ('tefap_eligible', models.CharField(blank=True, max_length=256, null=True)),
                ('agency_representative_signature', models.TextField(blank=True, null=True)),
                ('internal_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guestbook_sign_in.guest')),
            ],
        ),
    ]
